## Q1

In [1]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Q2

In [14]:
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

2
5
9
8
7
6
4
3
26
8
[ 2  5  9  8  7  6  4  3 26  8]
[ 2  3  4  5  6  7  8  8  9 26]


## Q3

In [22]:
a=np.array([1,2,3,4,5,6])
print(a.ndim)
print(a.size)
print(type(a))

1
6
<class 'numpy.ndarray'>


## Q4

In [23]:
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


## Q5

In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


## Q6

In [25]:
a = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3], dtype=int64))
